#!/usr/bin/env php
<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit('This command can only be run from the CLI.');
}

$rootPath = __DIR__;

$commands = [
    'cache:clear' => [
        'description' => 'Clear application and generated caches.',
        'script' => $rootPath . '/bin/cache-clear.php',
    ],

    'cache:config' => [
        'description' => 'Create the configuration cache.',
        'script' => $rootPath . '/bin/cache-config.php',
    ],

    'cache:route' => [
        'description' => 'Create the route cache.',
        'script' => $rootPath . '/bin/cache-route.php',
    ],
];

$argv = $_SERVER['argv'] ?? [];
$command = $argv[1] ?? 'list';
$arguments = array_slice($argv, 2);

if (in_array($command, ['list', '--help', '-h'], true)) {
    fwrite(STDOUT, "Pkathamo Command Line\n\n");
    fwrite(STDOUT, "Usage:\n");
    fwrite(STDOUT, "  php pkathamo <command> [options]\n\n");
    fwrite(STDOUT, "Available commands:\n");

    $width = max(array_map('strlen', array_keys($commands)));

    foreach ($commands as $name => $definition) {
        fwrite(
            STDOUT,
            sprintf(
                "  %-{$width}s  %s\n",
                $name,
                $definition['description']
            )
        );
    }

    exit(0);
}

if (!isset($commands[$command])) {
    fwrite(STDERR, "Unknown command: {$command}\n\n");
    fwrite(STDERR, "Run `php pkathamo list` to see available commands.\n");

    exit(1);
}

$script = $commands[$command]['script'];

if (!is_file($script)) {
    fwrite(STDERR, "Command script does not exist: {$script}\n");

    exit(1);
}

require $script;